# Core prompt elements
[character]
success_symbol = "[\uf0a9](bold)"
error_symbol = "[\uf0a9](bold red)"

[username]
style_user = "bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold purple) '
trim_at = "."
disabled = false

[directory]
read_only = " "
truncation_length = 10
truncate_to_repo = true
style = "bold italic blue"

[cmd_duration]
min_time = 4
show_milliseconds = false
style = "bold italic red"

# Git configuration
[git_branch]
symbol = 'git:'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)"
modified = "[${count}+](yellow)"
deleted = "[${count}-](red)"
conflicted = "[${count}~](red)"
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](blue)"
staged = "[${count}+](green)"

[git_state]
style = "bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"
revert = "revert"
cherry_pick = "cherry"
bisect = "bisect"
am = "am"
am_or_rebase = "am/rebase"

# Docker
[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]

# Disabled language modules
[golang]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[haskell]
disabled = true

[nim]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[nodejs]
disabled = true

# Disabled other modules
[aws]
disabled = true

[conda]
disabled = true

[dart]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[hg_branch]
disabled = true

[memory_usage]
disabled = true

[nix_shell]
disabled = true

[package]
disabled = true

[shlvl]
disabled = true
